start-at-login = true
after-login-command = []

after-startup-command = [
	'exec-and-forget sketchybar',
	'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

exec-on-workspace-change = [
	'/bin/bash',
	'-c',
	'sketchybar --trigger aerospace_workspace_changed FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

on-focus-changed = [
	'move-mouse window-lazy-center',
	'exec-and-forget /bin/bash -c "~/.config/aerospace/toggle_sketchybar.sh"',
	'exec-and-forget sketchybar --trigger front_app_switched',
	'exec-and-forget sketchybar --trigger update_windows'
]


on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
default-root-container-layout = 'tiles'

[gaps]
outer.left = 4
outer.right = 4
outer.top = [{ monitor.main = 4 }, { monitor.secondary = 37 }, 30]

[mode.main.binding]
alt-w = ['focus up', 'exec-and-forget sketchybar --trigger change-focused-window']
alt-a = ['focus left', 'exec-and-forget sketchybar --trigger change-focused-window']
alt-r = ['focus down', 'exec-and-forget sketchybar --trigger change-focused-window']
alt-s = ['focus right', 'exec-and-forget sketchybar --trigger change-focused-window']


alt-shift-w = ['move up', 'exec-and-forget sketchybar --trigger move-window']
alt-shift-a = ['move left', 'exec-and-forget sketchybar --trigger move-window']
alt-shift-r = ['move down', 'exec-and-forget sketchybar --trigger move-window']
alt-shift-s = ['move right', 'exec-and-forget sketchybar --trigger move-window']

alt-q = 'join-with left'
alt-f = 'fullscreen --no-outer-gaps'


alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

alt-1 = ['workspace 1', 'exec-and-forget sketchybar --trigger change-focused-workspace']
alt-2 = ['workspace 2', 'exec-and-forget sketchybar --trigger change-focused-workspace']
alt-3 = ['workspace 3', 'exec-and-forget sketchybar --trigger change-focused-workspace']
alt-4 = ['workspace 4', 'exec-and-forget sketchybar --trigger change-focused-workspace']
alt-5 = ['workspace 5', 'exec-and-forget sketchybar --trigger change-focused-workspace']
alt-6 = ['workspace 6', 'exec-and-forget sketchybar --trigger change-focused-workspace']
alt-7 = ['workspace 7', 'exec-and-forget sketchybar --trigger change-focused-workspace']
alt-8 = ['workspace 8', 'exec-and-forget sketchybar --trigger change-focused-workspace']
alt-9 = ['workspace 9', 'exec-and-forget sketchybar --trigger change-focused-workspace']
alt-0 = ['workspace 10', 'exec-and-forget sketchybar --trigger change-focused-workspace']

alt-shift-1 = ['move-node-to-workspace 1', 'exec-and-forget sketchybar --trigger move-window']
alt-shift-2 = ['move-node-to-workspace 2', 'exec-and-forget sketchybar --trigger move-window']
alt-shift-3 = ['move-node-to-workspace 3', 'exec-and-forget sketchybar --trigger move-window']
alt-shift-4 = ['move-node-to-workspace 4', 'exec-and-forget sketchybar --trigger move-window']
alt-shift-5 = ['move-node-to-workspace 5', 'exec-and-forget sketchybar --trigger move-window']
alt-shift-6 = ['move-node-to-workspace 6', 'exec-and-forget sketchybar --trigger move-window']
alt-shift-7 = ['move-node-to-workspace 7', 'exec-and-forget sketchybar --trigger move-window']
alt-shift-8 = ['move-node-to-workspace 8', 'exec-and-forget sketchybar --trigger move-window']
alt-shift-9 = ['move-node-to-workspace 9', 'exec-and-forget sketchybar --trigger move-window']
alt-shift-0 = ['move-node-to-workspace 10', 'exec-and-forget sketchybar --trigger move-window']

alt-z = 'mode resize'


[mode.resize.binding]
w = 'resize height +50'
a = 'resize width -50'
r = 'resize height -50'
s = 'resize width +50'
esc = 'mode main'

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'secondary'

[key-mapping.key-notation-to-key-code]
q = 'q'
w = 'w'
f = 'e'
p = 'r'
g = 't'
j = 'y'
l = 'u'
u = 'i'
y = 'o'
semicolon = 'p'
leftSquareBracket = 'leftSquareBracket'
rightSquareBracket = 'rightSquareBracket'
backslash = 'backslash'

a = 'a'
r = 's'
s = 'd'
t = 'f'
d = 'g'
h = 'h'
n = 'j'
e = 'k'
i = 'l'
o = 'semicolon'
quote = 'quote'

z = 'z'
x = 'x'
c = 'c'
v = 'v'
b = 'b'
k = 'n'
m = 'm'
comma = 'comma'
period = 'period'
slash = 'slash'
