require("items.widgets.calendar")
require("items.widgets.battery")
require("items.widgets.volume")
require("items.widgets.wifi")
require("items.widgets.ram")
require("items.widgets.cpu")
require("items.widgets.btc")
